spring:
  application:
    name: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: admin

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      password:
      expired:
        defaultTime: 5
      repositories:
        enabled: false

aws:
  sns:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: ap-northeast-2

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

slack:
  token: ${SLACK_TOKEN}
