CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(255),
    password         VARCHAR(255),
    profile_media_id BIGINT,
    created_at       TIMESTAMP(6) NOT NULL,
    modified_at      TIMESTAMP(6) NOT NULL,
    deleted_at       TIMESTAMP(6)
);

CREATE TABLE follows
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT       NOT NULL,
    followee_id BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6)
);

CREATE INDEX idx_follows_follower_followee_active ON follows (follower_id, followee_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_follows_followee_active ON follows (followee_id) WHERE deleted_at IS NULL;

CREATE TABLE follow_counts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL UNIQUE,
    followers_count BIGINT       NOT NULL,
    followees_count BIGINT       NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    modified_at     TIMESTAMP(6) NOT NULL,
    deleted_at      TIMESTAMP(6)
);

CREATE INDEX idx_follow_counts_user_active ON follow_counts (user_id) WHERE deleted_at IS NULL;

CREATE TABLE posts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content      VARCHAR(1000) NOT NULL,
    user_id      BIGINT        NOT NULL,
    parent_id    BIGINT,
    quote_id     BIGINT,
    repost_id    BIGINT,
    repost_count INTEGER       NOT NULL DEFAULT 0,
    like_count   INTEGER       NOT NULL DEFAULT 0,
    reply_count  INTEGER       NOT NULL DEFAULT 0,
    view_count   BIGINT        NOT NULL DEFAULT 0,
    media_ids    BIGINT[],
    created_at   TIMESTAMP(6)  NOT NULL,
    modified_at  TIMESTAMP(6)  NOT NULL,
    deleted_at   TIMESTAMP(6)
);

CREATE INDEX idx_posts_created_at_active ON posts (created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_parent_created_at_active ON posts (parent_id, created_at ASC) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_user_post_created_at_active ON posts (user_id, created_at DESC) WHERE deleted_at IS NULL AND parent_id IS NULL;
CREATE INDEX idx_posts_user_reply_created_at_active ON posts (user_id, created_at DESC) WHERE deleted_at IS NULL AND parent_id IS NOT NULL;
CREATE INDEX idx_posts_user_quote_active ON posts (user_id, quote_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_user_repost_active ON posts (user_id, repost_id) WHERE deleted_at IS NULL;

CREATE TABLE likes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    post_id     BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6)
);

CREATE INDEX idx_likes_user_post_active ON likes (user_id, post_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_likes_user_created_at_active ON likes (user_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_likes_created_at_active ON likes (created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE media
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_type  VARCHAR(255)  NOT NULL,
    path        VARCHAR(2000) NOT NULL,
    status      VARCHAR(255)  NOT NULL,
    user_id     BIGINT,
    upload_id   VARCHAR(500),
    file_size   BIGINT,
    attributes  JSONB,
    created_at  TIMESTAMP(6)  NOT NULL,
    modified_at TIMESTAMP(6)  NOT NULL,
    deleted_at  TIMESTAMP(6)
);

CREATE INDEX idx_media_user_id_created_at_active ON media (user_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_media_parts_gin ON media USING GIN ((attributes -> 'parts')) WHERE deleted_at IS NULL;
